---

run-name: Publish GitHub Pages
name: Publish GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
          python-version: '3.8'
      - name: Install Doc Depedencies
        run: |
          pip3 install --upgrade pip
          pip3 install -r requirements.txt
      - name: Clone FUNWAVE-TVD 
        uses: actions/checkout@v3
        with:
          repository: fengyanshi/FUNWAVE-TVD
          path: src/external/FUNWAVE
      - name: Clone FUNWAVE-TVD Python Tools 
        uses: actions/checkout@v3
        with:
          repository: mayhl/FUNWAVE-TVD-Python-Tools
          path: src/external/FUNTOOL
          ref: main
      - name: Build Sphinx Docs
        run: |
          make html
        shell: bash
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5.2.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import-gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import-gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import-gpg.outputs.name }}"
          echo "email:       ${{ steps.import-gpg.outputs.email }}"
      - name: Clone Github Pages Branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages
      - name: Commit Changes
        run: |
          cd gh-pages
          # Removing all files (workaround for removing old files)
          git rm -r --ignore-unmatch *
          cp -r ../build/html/* .
          touch .nojekyll
          git add .
          git config user.email "${{ steps.import-gpg.outputs.email }}"
          git config user.name "${{ steps.import-gpg.outputs.name }}"
          NOW=$(date)
          git commit -S -m "Documentation Autoupdate ${NOW}" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
